### ISSUE TITLE
ESP8266 Power Save  GPIO pin for switch off power for WS2812

### ISSUE THREAD

**Issue by StefanM60** [diyhue/Lights#119]
the power consumption of the WS2812 is quite high with many LED's in standby. It would be great to have a GPIO pin that switches on the LED's as soon as they are on and switches off when the LED's are off for a certain time. With this a relay or FET could switch off the power supply of the WS2812.

Best regards Stefan

**Comment by mariusmotea** [comment]
i think this can be done, not sure if the strip require an initialization process once the power is applied back.

https://github.com/diyhue/Lights/blob/master/Arduino/Generic_WS2812_Strip/Generic_WS2812_Strip.ino#L391

you can choose a free GPIO, set it as OUTPUT in setup phase and you can add additional condition here:
https://github.com/diyhue/Lights/blob/master/Arduino/Generic_WS2812_Strip/Generic_WS2812_Strip.ino#L391

inTransition must be false (no animation is taking place) and lights[light].lightState must be false that show the logic power level.

<blockquote><img src="https://opengraph.githubassets.com/9258b9ccc63d8e18b49e0b75326ff38a1b6b9617eae18abbaf270d8bf830aee5/diyhue/Lights" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/diyhue/Lights">Lights/Generic_WS2812_Strip.ino at master · diyhue/Lights</a></strong></div><div>DIY lights with support for diyHue. Contribute to diyhue/Lights development by creating an account on GitHub.</div></blockquote>

**Comment by mariusmotea** [comment]
Hi

I found this feature more important since it may save lot of energy for long strips so i implement this feature. Is tested by me and currently it set a GPIO HIGH when the strip must be on. This is because i did not have a P-CHannel mosfet that can be fully controlled by the ESP, so i used an additional NPN transistor.

This is the commit:

https://github.com/diyhue/Lights/commit/1eea8658c09b4cfcc565c6130576285753f91d9f
