### ISSUE TITLE
My diyhue-ESP light is not found by my original Philips Hue Bridge

### ISSUE THREAD

**Issue by TimW2022** [diyhue/Lights#122]
Today I managed to build the app from

https://github.com/diyhue/Lights/tree/master/Arduino/Generic_RGB_CCT_Light

and got it flashed on ESP8266-ESP12F module. All 5 PWM outputs are operational and controllable via the ESP websever GUI. That is great. But my Philips Hue-Bridge is not detecting any new lamp. The new ESP-diy-lamp has stable wifi connection and is controllable via Web, also during the search.

Is there anything I need to add or to configure in the app that it can be found by the Philips-Hue-Bridge ?

The philiphs hue bridge detects my (non philips) zigbee lamps fine, but I never tried this with a wifi lamp. I assume it polls out over Ethernet and my ftirtzbox-Wifi-AP to search wifi lamps in parallel to zigbee lamps, but I don't know. Will go for some wireshark work the next days.

Thanks in advance
Tim

**Comment by Mevel** [comment]
Diyhue lights will never work with original hue bridge.
Not just because the vendor doesn't like it but simply because it uses two different communication technologies.

Zigbee is like wifi at 2.4Ghz but it is does not work together hence no interference with wifi and vice versa. 

That's what the diyhue emulator is for. It emulates a original hue bridge with the benefits of using a variety of devices across vendors.

You can start your own instance and add the diyhue light there.

You can also add your lights connected to original bridge to diyhue. (unfortunately no sensors and switches are exposed) 

Enjoy

**Comment by TimW2022** [comment]
Thanks for the fast feedback Mevel !
