### ISSUE TITLE
Arduino nano 33 IoT support

### ISSUE THREAD

**Issue by Obi-Stan-Kenobi** [diyhue/Lights#125]
I was wondering if it is possible to make the Gradien Strip code work on an Arduino nano 33 IoT.

**Comment by mariusmotea** [comment]
Unfortunately we don't maintain the entire code, we rely on certain libraries so if these libraries are supporting also Arduino nano 33 IoT it must work. Did you tried to compile the code and get errors? I think a small change is require to NeopixelBus library to specify the strip data in pin (on ESP8266 is not specified since just RX pin is working) and also change wifi connection code with the one for Arduino nano 33 IoT (probably you need to remove WiFI Manager library that is made for ESP8266). Not having such board is hard for me to change the code for it.

**Comment by Obi-Stan-Kenobi** [comment]
Thank you, I will try this asap.
I did get a compiling error though, the LittleFS.h: no such file or directory.

**Comment by mariusmotea** [comment]
Look in the other sketches where SPIFFS is still used. ESP library migrated to LittleFS and consider SPIFFS deprecated, for this reason we did the switch. In the sketch you need to rename LittleFS with SPIFFS and in the header import FS.h instead of LittleFS.h

**Comment by mariusmotea** [comment]
Look, this is still using SPIFFS: https://github.com/diyhue/Lights/blob/master/Arduino/Generic_WS2812_Strip/Generic_WS2812_Strip.ino

<blockquote><img src="https://opengraph.githubassets.com/39bd084cbe1e08a4f570180909dcdd37560a4bc8db04eed698b4e64a5bf2ce5d/diyhue/Lights" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/diyhue/Lights">Lights/Generic_WS2812_Strip.ino at master · diyhue/Lights</a></strong></div><div>DIY lights with support for diyHue. Contribute to diyhue/Lights development by creating an account on GitHub.</div></blockquote>
