### ISSUE TITLE
Wifi AP

### ISSUE THREAD

**Issue by gastonMM** [diyhue/Lights#82]
Hello, I have 3 ESP8266, with the Generic_WS2812_Strip.bin firmware, and after connecting to the wifi network, the AP continues with the captive page.

Also try Generic_WS2812_Strip.ino, with the same result.

**Comment by gastonMM** [comment]
screenshot
https://drive.google.com/file/d/1htc1saRM0LcGGdBxrgkBWMXJJTjErGyS/view?usp=sharing

<blockquote><img src="https://lh6.googleusercontent.com/y9md53Ns4AUFLlGqXygRrBheuQhJrFIBP5xak5p68G5lTkiP2wwYz6XXu6JBEtM=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1htc1saRM0LcGGdBxrgkBWMXJJTjErGyS/view?usp=sharing&usp=embed_facebook">Screenshot_20200612-081942.png</a></strong></div></blockquote>

**Comment by mariusmotea** [comment]
This happens if the wifi was not ready during ESP8266 boot. Is an annoying bug. 
The issue is with wifimanager and at this line:

https://github.com/diyhue/Lights/blob/master/Arduino/Generic_WS2812_Strip/Generic_WS2812_Strip.ino#L623


<blockquote><img src="https://avatars3.githubusercontent.com/u/45603380?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/diyhue/Lights">diyhue/Lights</a></strong></div><div>DIY lights with support for diyHue. Contribute to diyhue/Lights development by creating an account on GitHub.</div></blockquote>

**Comment by gastonMM** [comment]
Do you have any template without wifi manager? that allows to put ssid and password

try to replace it with the following data but fail to load it

```
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#ifndef STASSID
#define STASSID "your-ssid"
#define STAPSK  "your-password"
#endif

const char* ssid     = STASSID;
const char* password = STAPSK;

const char* host = "192.168.1.1";
const uint16_t port = 3000;

ESP8266WiFiMulti WiFiMulti;

void setup() {
  Serial.begin(115200);

  // We start by connecting to a WiFi network
  WiFi.mode(WIFI_STA);
  WiFiMulti.addAP(ssid, password);

  Serial.println();
  Serial.println();
  Serial.print("Wait for WiFi... ");

  while (WiFiMulti.run() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  delay(500);
}
```

**Comment by mariusmotea** [comment]
Look here: https://github.com/tzapu/WiFiManager/

> //first parameter is name of access point, second is the password
wifiManager.autoConnect("AP-NAME", "AP-PASSWORD");

<blockquote><img src="https://avatars0.githubusercontent.com/u/2983312?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/tzapu/WiFiManager">tzapu/WiFiManager</a></strong></div><div>ESP8266 WiFi Connection manager with web captive portal - tzapu/WiFiManager</div></blockquote>
